[theme]
base = "light"
primaryColor = "#087F8C"
backgroundColor = "#F6F8FA"
secondaryBackgroundColor = "#EDF2F5"
textColor = "#163047"
font = "sans serif"

[browser]
gatherUsageStats = false

[server]
headless = true
address = "127.0.0.1"
